### ISSUE TITLE
Open Wiki issues - 7/26

### ISSUE THREAD

**Issue by MichaelSchwar3** [IrieY56/dissonance#3]
Schema

- [x] Do we need both username and e-mail?

- [x] For servers you may want to create flag like “Private” false/true which will distinguish between a direct message and a public server

Sample State

- [x] Why do we need to keep track of the users’ message ids? I see it where we are iterating over all of our messages and refering back to the user rather than the other way around

**Comment by IrieY56** [comment]
- Removed email from schema
- Added a private boolean column for servers to schema

- Removed message id array from sample state.
